apiRules:
- include:
    uidRegex: ^XRTK.+
    type: Namespace
- exclude:
    uidRegex: ^Unity.+
    type: Namespace
- exclude:
    uidRegex: ^Leap.+
    type: Namespace
- exclude:
    uidRegex: ^LeapInternal.+
    type: Namespace
- exclude:
    uidRegex: ^LeapMotion.+
    type: Namespace
